# Generated by Django 3.0.6 on 2020-05-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contacts_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('slogan', models.CharField(max_length=50, null=True)),
                ('words', models.CharField(max_length=50, null=True)),
                ('text', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
