# Generated by Django 3.0.6 on 2020-05-04 12:34

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('photo_1', models.ImageField(upload_to=main.models.About.get_file_name_about)),
                ('photo_2', models.ImageField(upload_to=main.models.About.get_file_name_about)),
            ],
        ),
    ]
